Algoritmo "lista1 (atividade 14)"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 25/03/2023
Var
 dia,km,total:real


Inicio
escreva("Quantos dias ficou com o carro: ")
leia(dia)
escreva("Quantos km pecorreu: ")
leia(km)
total<-(dia*90) + (km*0.20)
escreva("O total a ser pagor por ",dia," dias e",km,"km é :",total,"R$" )





Fimalgoritmo