Algoritmo "lista1 (atividade 3)"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 25/03/2023
Var
    salario:real
    funcionario : caractere

Inicio
escreva("Nome do Funcionário: ")
leia(funcionario)
escreva("Salário: ")
leia(salario)
escreva(" O funcionário ", funcionario, " tem um salário de R$" , salario, " em Junho.")


Fimalgoritmo