Algoritmo "lista1 (atividade 10)"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 25/03/2023
Var
   largura, altura, metro2, tinta :real


Inicio
escreva("Digite a largura: ")
leia(largura)
escreva("Digite a altura: ")
leia(altura)
metro2 <- (altura * largura)
tinta<- metro2/2
escreva("Para pintar",metro2,"m²", " é preciso", tinta," litros de tinta")






Fimalgoritmo