Algoritmo "lista1 (atividade 16)"
//
//
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 25/03/2023
Var
 cigarrosD,ano,cigarro,minuto :real


Inicio
escreva("Quantos cigarros fuma por dia: ")
leia(cigarrosD)
escreva("Há quantos anos fuma: ")
leia(ano)
cigarro<- cigarrosd * (365*ano)
minuto <- (cigarro * 10)/1440
escreva("você pederá " ,minuto:5:0, " dias da sua via")






Fimalgoritmo