Algoritmo "lista1 (atividade 4)"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 25/03/2023
Var
    valor1 , valor2 , soma :real


Inicio
escreva("Digite um valor: ")
leia(valor1)
escreva("Digite outro valor: ")
leia(valor2)
soma <- valor1 + valor2
escreva(" A soma entre",valor1 ," e ",  valor2, " é igual a ", soma )


Fimalgoritmo