Algoritmo "lista1 (atividade 7)"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 25/03/2023
Var
    numero, dobro , terca_parte :real


Inicio
escreva("Digite um número: ")
leia(numero)
dobro <- numero * 2
terca_parte <- numero/3
escreval("O dobro de " , numero , " é " , dobro:4:2)
escreval("A terça parte de " ,numero , " é ",terca_parte:4:2)



Fimalgoritmo